### ISSUE TITLE
Shifted from Nexus: Error downloading Caprica and issue with Drive access

### ISSUE THREAD

**Issue by Picklelord** [Picklelord/sf_modding_template#1]
![image](https://github.com/Picklelord/sf_modding_template/assets/25780501/9b107ad8-62c0-4b10-9086-5a5da8599698)

This is what I get from running the setup. My steam install is on G drive but my games is on C drive. Which i have properly pointed to each of those in the setup.json. Same issue with or without admin priv. My guess is its not using the install location for finding/copying the ini files and the error with BAE looks like a typo in the script.

Can confirm that caprica link still does not work work for me. 404 error.

**Comment by vendeta44** [comment]
my config file. 

{
  "starfieldInstallLocation": "G:/SteamLibrary/steamapps/common/Starfield",
  "starfieldMyGamesLocation": "C:/Users/vendeta/Documents/My Games/Starfield",
  "pyinstallerLocation": "C:/Users/Vendeta/AppData/Roaming/Python/Python310/Scripts",
  "skipPSC_MassCompile": false,
  "doTextureDataShift": true,
  "doBuildBeforeInstall": true,
  "doDeleteBuildAfterInstall": true,
  "baseDataModsPath": "src/base_data_mods/",
  "gamesDataModsPath": "src/my_games_data_mods/",
  "iniModsPath": "src/ini_mods/",
  "pscModsPath": "src/psc_mods/",
  "baseModsPath": "src/base_mods/",
  "starfieldFlagsLocation": "reference/Starfield_Papyrus_Flags.flg",
  "starfieldDecompiledScriptsLocation": "reference/StarfieldScriptsReference",
  "starfieldCompileOutputLocation": "build/installDir_Starfield/Data/scripts",
  "starfieldBaseBuildLocation": "build/installDir_Starfield",
  "starfieldMyGameBuildLocation": "build/MyGames_Starfield",
  "capricaUrl": "https://github.com/Orvid/Caprica/suites/16483071879/artifacts/941884665",
  "sevenZipUrl": "https://www.7-zip.org/a/7z2301-x64.exe",
  "champollionUrl": "https://github.com/Orvid/Champollion/releases/download/v1.3.1/Champollion.1.3.1.7z",
  "starfieldFlagsUrl": "https://raw.githubusercontent.com/Orvid/Caprica/9cd6d32ec2750adae329e81f7276dac95251e000/test/Starfield_Papyrus_Flags.flg",
  "baeManualUrl": "https://www.nexusmods.com/starfield/mods/165?tab:files&file_id:775"
}

**Comment by Picklelord** [comment]
Thanks for that, it all looks good to me, so there must be something up with the bat file.. 
Can you right click and edit the setup_venv.bat and change the first line from "@echo off" to "@echo on" and run it through cmd again, hopefully that will pin point where the issue is.

**Comment by vendeta44** [comment]
```
G:\>G:\SFmoddin\Release-0.1.1\setup_venv.bat

G:\>setlocal ENABLEDELAYEDEXPANSION

G:\>set ROOT_DIR=G:\SFmoddin\Release-0.1.1\

G:\>FOR /F "usebackq tokens=*" %i IN (`powershell -command "$json = Get-Content -Raw -Path G:\SFmoddin\Release-0.1.1\config.json | ConvertFrom-Json; $json.starfieldInstallLocation"`) DO SET starfieldInstallLocation="!ROOT_DIR!%i"

G:\>SET starfieldInstallLocation="!ROOT_DIR!G:/SteamLibrary/steamapps/common/Starfield/"

G:\>FOR /F "usebackq tokens=*" %i IN (`powershell -command "$json = Get-Content -Raw -Path G:\SFmoddin\Release-0.1.1\config.json | ConvertFrom-Json; $json.starfieldMyGamesLocation"`) DO SET starfieldMyGamesLocation="!ROOT_DIR!%i"

G:\>SET starfieldMyGamesLocation="!ROOT_DIR!C:/Users/vendeta/Documents/My Games/Starfield/"

G:\>FOR /F "usebackq tokens=*" %i IN (`powershell -command "$json = Get-Content -Raw -Path G:\SFmoddin\Release-0.1.1\config.json | ConvertFrom-Json; $json.iniModsPath"`) DO SET iniModsPath="!ROOT_DIR!%i"

G:\>SET iniModsPath="!ROOT_DIR!src/ini_mods/"

G:\>FOR /F "usebackq tokens=*" %i IN (`powershell -command "$json = Get-Content -Raw -Path G:\SFmoddin\Release-0.1.1\config.json | ConvertFrom-Json; $json.starfieldDecompiledScriptsLocation"`) DO SET starfieldDecompiledScriptsLocation="!ROOT_DIR!%i"

G:\>SET starfieldDecompiledScriptsLocation="!ROOT_DIR!reference/StarfieldScriptsReference"

G:\>FOR /F "usebackq tokens=*" %i IN (`powershell -command "$json = Get-Content -Raw -Path G:\SFmoddin\Release-0.1.1\config.json | ConvertFrom-Json; $json.sevenZipUrl"`) DO SET sevenZipUrl=%i

G:\>SET sevenZipUrl=https://www.7-zip.org/a/7z2301-x64.exe

G:\>FOR /F "usebackq tokens=*" %i IN (`powershell -command "$json = Get-Content -Raw -Path G:\SFmoddin\Release-0.1.1\config.json | ConvertFrom-Json; $json.capricaUrl"`) DO SET capricaUrl=%i

G:\>SET capricaUrl=https://github.com/Orvid/Caprica/suites/16483071879/artifacts/941884665

G:\>FOR /F "usebackq tokens=*" %i IN (`powershell -command "$json = Get-Content -Raw -Path G:\SFmoddin\Release-0.1.1\config.json | ConvertFrom-Json; $json.champollionUrl"`) DO SET champollionUrl=%i

G:\>SET champollionUrl=https://github.com/Orvid/Champollion/releases/download/v1.3.1/Champollion.1.3.1.7z

G:\>FOR /F "usebackq tokens=*" %i IN (`powershell -command "$json = Get-Content -Raw -Path G:\SFmoddin\Release-0.1.1\config.json | ConvertFrom-Json; $json.starfieldFlagsUrl"`) DO SET starfieldFlagsUrl=%i

G:\>SET starfieldFlagsUrl=https://raw.githubusercontent.com/Orvid/Caprica/9cd6d32ec2750adae329e81f7276dac95251e000/test/Starfield_Papyrus_Flags.flg

G:\>FOR /F "usebackq tokens=*" %i IN (`powershell -command "$json = Get-Content -Raw -Path G:\SFmoddin\Release-0.1.1\config.json | ConvertFrom-Json; $json.baeManualUrl"`) DO SET baeManualUrl=%i

G:\>SET baeManualUrl=https://www.nexusmods.com/starfield/mods/165?tab:files&file_id:775

G:\>echo ----------------------------------------
----------------------------------------

G:\>echo Collecting existing INI files from Game Install
Collecting existing INI files from Game Install

G:\>IF EXIST "!starfieldMyGamesLocation:" !\StarfieldCustom.ini" && NOT EXISTS "!iniModsPath:"=!StarfieldCustom.ini\original.ini" (

G:\>echo Making a copy of the existing StarfieldCustom.ini to be used in compiling
Making a copy of the existing StarfieldCustom.ini to be used in compiling

G:\>if not exist "!iniModsPath:\StarfieldCustom.ini\" mkdir "!iniModsPath:\StarfieldCustom.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldMyGamesLocation:"=!\StarfieldCustom.ini" "!iniModsPath:"=!StarfieldCustom.ini\original.ini"
File not found - StarfieldCustom.ini
0 File(s) copied

G:\>IF EXIST "!starfieldMyGamesLocation:" !\StarfieldPrefs.ini" && NOT EXISTS "!iniModsPath:"=!StarfieldPrefs.ini\original.ini"(

G:\>echo Making a copy of the existing StarfieldPrefs.ini to be used in compiling
Making a copy of the existing StarfieldPrefs.ini to be used in compiling

G:\>if not exist "!iniModsPath:\StarfieldPrefs.ini\" mkdir "!iniModsPath:\StarfieldPrefs.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldMyGamesLocation:"=!\StarfieldPrefs.ini" "!iniModsPath:"=!StarfieldPrefs.ini\original.ini"
File not found - StarfieldPrefs.ini
0 File(s) copied

G:\>IF EXIST "!starfieldMyGamesLocation:" !\StarfieldHotkeys.ini" && NOT EXISTS "!iniModsPath:"=!StarfieldHotkeys.ini\original.ini"(

G:\>echo Making a copy of the existing StarfieldHotkeys.ini to be used in compiling
Making a copy of the existing StarfieldHotkeys.ini to be used in compiling

G:\>if not exist "!iniModsPath:\StarfieldHotkeys.ini\" mkdir "!iniModsPath:\StarfieldHotkeys.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldMyGamesLocation:"=!\StarfieldHotkeys.ini" "!iniModsPath:"=!StarfieldHotkeys.ini\original.ini"
File not found - StarfieldHotkeys.ini
0 File(s) copied

G:\>IF EXIST "!starfieldInstallLocation:" !\Starfield.ini" && NOT EXISTS "!iniModsPath:"=!Starfield.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\Starfield.ini\" mkdir "!iniModsPath:\Starfield.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\Starfield.ini" "!iniModsPath:"=!Starfield.ini\original.ini"
File not found - Starfield.ini
0 File(s) copied

G:\>IF EXIST "!starfieldInstallLocation:" !\StartingCommands.txt" && NOT EXISTS "!iniModsPath:"=!StartingCommands.txt\original.txt"(

G:\>echo Making a copy of the existing StartingCommands.txt to be used in compiling
Making a copy of the existing StartingCommands.txt to be used in compiling

G:\>if not exist "!iniModsPath:\StartingCommands.txt\" mkdir "!iniModsPath:\StartingCommands.txt\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\StartingCommands.txt" "!iniModsPath:"=!StartingCommands.txt\original.txt"
File not found - StartingCommands.txt
0 File(s) copied

G:\>IF EXIST "!starfieldInstallLocation:" !\Low.ini" && NOT EXISTS "!iniModsPath:"=!Low.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\Low.ini\" mkdir "!iniModsPath:\Low.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\Low.ini" "!iniModsPath:"=!Low.ini\original.ini"
File not found - Low.ini
0 File(s) copied

G:\>IF EXIST "!starfieldInstallLocation:" !\Medium.ini" && NOT EXISTS "!iniModsPath:"=!Medium.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\Medium.ini\" mkdir "!iniModsPath:\Medium.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\Medium.ini" "!iniModsPath:"=!Medium.ini\original.ini"
File not found - Medium.ini
0 File(s) copied

G:\>IF EXIST "!starfieldInstallLocation:" !\High.ini" && NOT EXISTS "!iniModsPath:"=!High.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\High.ini\" mkdir "!iniModsPath:\High.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\High.ini" "!iniModsPath:"=!High.ini\original.ini"
File not found - High.ini
0 File(s) copied

G:\>IF EXIST "!starfieldInstallLocation:" !\Ultra.ini" && NOT EXISTS "!iniModsPath:"=!Ultra.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\Ultra.ini\" mkdir "!iniModsPath:\Ultra.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\Ultra.ini" "!iniModsPath:"=!Ultra.ini\original.ini"
File not found - Ultra.ini
0 File(s) copied

G:\>echo ----------------------------------------
----------------------------------------

G:\>echo Attempting to install Caprica.exe
Attempting to install Caprica.exe

G:\>IF NOT EXIST G:\SFmoddin\Release-0.1.1\apps\Caprica.exe (
powershell -Command "Add-Type -AssemblyName System.Windows.Forms; $response = [System.Windows.Forms.MessageBox]::Show('We need you to manually download the Caprica.exe Artifact and place it into the .apps\ directory, click Ok and we will attempt to download it. Install it in and give further instructions in the console.', 'Manual Download Required', [System.Windows.Forms.MessageBoxButtons]::Ok"
 echo Unable to automatically download the Caprica Artifact, please install it manually
 echo Attempting to download it now, if it doesnt download, download it here:
 echo https://github.com/Orvid/Caprica/suites/16483071879/artifacts/941884665
 echo Place it here: "G:\SFmoddin\Release-0.1.1\apps\Caprica.exe"
 start "" "https://github.com/Orvid/Caprica/suites/16483071879/artifacts/941884665"
 start explorer.exe "C:\Users\vendeta\Downloads"
 set /p userinput="Have you placed the Caprica.exe in the location specified above? (Y): "
)  ELSE (echo Caprica Found! )
Caprica Found

G:\>echo ----------------------------------------
----------------------------------------

G:\>echo Attempting to install 7z.exe
Attempting to install 7z.exe

G:\>IF NOT EXIST G:\SFmoddin\Release-0.1.1\apps\7z.exe (IF EXIST "C:\Program Files\7-Zip\7z.exe" (
set sevenZipLocation="C:\Program Files\7-Zip\"
 echo 7z Found!
)  ELSE (
call bitsadmin /transfer 7z_Download https://www.7-zip.org/a/7z2301-x64.exe G:\SFmoddin\Release-0.1.1\cache\7z.exe
 start G:\SFmoddin\Release-0.1.1\cache\7z.exe
 set /p userinput="Have you installed 7z.exe? (Y): "
 del G:\SFmoddin\Release-0.1.1\cache\7z.exe
) )  ELSE (echo 7z Found! )
7z Found

G:\>echo ----------------------------------------
----------------------------------------

G:\>echo Attempting to install Champollion.exe
Attempting to install Champollion.exe

G:\>IF NOT EXIST G:\SFmoddin\Release-0.1.1\apps\Champollion.exe (
call bitsadmin /transfer Champollion_Download https://github.com/Orvid/Champollion/releases/download/v1.3.1/Champollion.1.3.1.7z G:\SFmoddin\Release-0.1.1\cache\Champollion.7z
 "C:\Program Files\7-Zip\"7z.exe e G:\SFmoddin\Release-0.1.1\cache\Champollion.7z Champollion.exe -oG:\SFmoddin\Release-0.1.1\apps\ Champollion.exe
 del G:\SFmoddin\Release-0.1.1\cache\Champollion.7z
)  ELSE (echo Champollion Found! )
Champollion Found

G:\>echo ----------------------------------------
----------------------------------------

G:\>echo Attempting to install Starfield_Papyrus_Flags.flg
Attempting to install Starfield_Papyrus_Flags.flg

G:\>IF NOT EXIST G:\SFmoddin\Release-0.1.1\reference\Starfield_Papyrus_Flags.flg (call bitsadmin /transfer Starfield_Papyrus_Flags_Download https://raw.githubusercontent.com/Orvid/Caprica/9cd6d32ec2750adae329e81f7276dac95251e000/test/Starfield_Papyrus_Flags.flg G:\SFmoddin\Release-0.1.1\reference\Starfield_Papyrus_Flags.flg )  ELSE (echo Starfield_Papyrus_Flags.flg Found! )
Starfield_Papyrus_Flags.flg Found

G:\>echo ----------------------------------------
----------------------------------------

G:\>echo Check for install of bae.exe
Check for install of bae.exe
( was unexpected at this time.

G:\>  IF  == "Y" (

G:\>
```

**Comment by Picklelord** [comment]
Hey Vendeta, I have released a new version, I have updated the setup_venv.bat and config.json files, and that should resolve the issues you are seeing. please let me know if it works and I will close the bug!

**Comment by vendeta44** [comment]
Thanks. Looks like that did the ticket on getting BAE to extract the scripts. However Its still struggling with ini's and on the python section.

I had to change the config to point to "C:\Users\vendeta\AppData\Local\Programs\Python\Python312" as the directory original stated didn't contain anything. After that it stopped throwing the "please install python 3.9+" warning. But it still doesn't want to build the compilers and does this.

```
G:\>echo Build INI and TXT python compilers
Build INI and TXT python compilers

G:\>cd G:\SFmoddin\Release-0.1.1\src\python_tools\
The syntax of the command is incorrect.

G:\SFmoddin\Release-0.1.1\src\python_tools>  IF EXIST  (

G:\>

```
And ya INI files still don't seem to want to copy. 

```
Collecting existing INI files from Game Install
Making a copy of the existing StarfieldCustom.ini to be used in compiling
The filename, directory name, or volume label syntax is incorrect.
File not found - original.ini
0 File(s) copied
Making a copy of the existing StarfieldPrefs.ini to be used in compiling
The filename, directory name, or volume label syntax is incorrect.
File not found - original.ini
0 File(s) copied
Making a copy of the existing StarfieldHotkeys.ini to be used in compiling
The filename, directory name, or volume label syntax is incorrect.
File not found - original.ini
0 File(s) copied
Making a copy of the existing Starfield.ini to be used in compiling
The filename, directory name, or volume label syntax is incorrect.
File not found - original.ini
0 File(s) copied
Making a copy of the existing StartingCommands.txt to be used in compiling
The filename, directory name, or volume label syntax is incorrect.
File not found - original.txt
0 File(s) copied
Making a copy of the existing Starfield.ini to be used in compiling
The filename, directory name, or volume label syntax is incorrect.
File not found - original.ini
0 File(s) copied
Making a copy of the existing Starfield.ini to be used in compiling
The filename, directory name, or volume label syntax is incorrect.
File not found - original.ini
0 File(s) copied
Making a copy of the existing Starfield.ini to be used in compiling
The filename, directory name, or volume label syntax is incorrect.
File not found - original.ini
0 File(s) copied
Making a copy of the existing Starfield.ini to be used in compiling
The filename, directory name, or volume label syntax is incorrect.
File not found - original.ini
0 File(s) copied
```

**Comment by Picklelord** [comment]
Have you set it to this in the config?: "C:/Users/Vendeta/AppData/Roaming/Python/Python312/Scripts"

I'm not able to replecate the ini issues, they are all found on my computer, can you show me the full path to where the Starfield.ini file is located and also the StarfieldPrefs.ini from your game install path and the My Games folder? 

Can you also edit the setup_venv.bat and replace this section below with this edited version?
We should get the paths its using to find the ini files printed out and find the issue..
 
```
echo ----------------------------------------
echo Collecting existing INI files from Game Install
echo "!starfieldMyGamesLocation:"=!\StarfieldCustom.ini"
IF EXIST "!starfieldMyGamesLocation:"=!\StarfieldCustom.ini" && NOT EXISTS "!iniModsPath:"=!StarfieldCustom.ini\original.ini" (
  echo Making a copy of the existing StarfieldCustom.ini to be used in compiling
  if not exist "!iniModsPath:\StarfieldCustom.ini\" mkdir "!iniModsPath:\StarfieldCustom.ini\"
  echo F|xcopy /Y /E "!starfieldMyGamesLocation:"=!\StarfieldCustom.ini" "!iniModsPath:"=!StarfieldCustom.ini\original.ini"
)
echo "!starfieldMyGamesLocation:"=!\StarfieldPrefs.ini"
IF EXIST "!starfieldMyGamesLocation:"=!\StarfieldPrefs.ini" && NOT EXISTS "!iniModsPath:"=!StarfieldPrefs.ini\original.ini"(
  echo Making a copy of the existing StarfieldPrefs.ini to be used in compiling
  if not exist "!iniModsPath:\StarfieldPrefs.ini\" mkdir "!iniModsPath:\StarfieldPrefs.ini\"
  echo F|xcopy /Y /E "!starfieldMyGamesLocation:"=!\StarfieldPrefs.ini" "!iniModsPath:"=!StarfieldPrefs.ini\original.ini"
)
echo "!starfieldMyGamesLocation:"=!\StarfieldHotkeys.ini"
IF EXIST "!starfieldMyGamesLocation:"=!\StarfieldHotkeys.ini" && NOT EXISTS "!iniModsPath:"=!StarfieldHotkeys.ini\original.ini"(
  echo Making a copy of the existing StarfieldHotkeys.ini to be used in compiling
  if not exist "!iniModsPath:\StarfieldHotkeys.ini\" mkdir "!iniModsPath:\StarfieldHotkeys.ini\"
  echo F|xcopy /Y /E "!starfieldMyGamesLocation:"=!\StarfieldHotkeys.ini" "!iniModsPath:"=!StarfieldHotkeys.ini\original.ini"
)
echo "!starfieldInstallLocation:"=!\Starfield.ini"
IF EXIST "!starfieldInstallLocation:"=!\Starfield.ini" && NOT EXISTS "!iniModsPath:"=!Starfield.ini\original.ini"(
  echo Making a copy of the existing Starfield.ini to be used in compiling
  if not exist "!iniModsPath:\Starfield.ini\" mkdir "!iniModsPath:\Starfield.ini\"
  echo F|xcopy /Y /E "!starfieldInstallLocation:"=!\Starfield.ini" "!iniModsPath:"=!Starfield.ini\original.ini"
)
echo "!starfieldInstallLocation:"=!\StartingCommands.txt"
IF EXIST "!starfieldInstallLocation:"=!\StartingCommands.txt" && NOT EXISTS "!iniModsPath:"=!StartingCommands.txt\original.txt"(
  echo Making a copy of the existing StartingCommands.txt to be used in compiling
  if not exist "!iniModsPath:\StartingCommands.txt\" mkdir "!iniModsPath:\StartingCommands.txt\"
  echo F|xcopy /Y /E "!starfieldInstallLocation:"=!\StartingCommands.txt" "!iniModsPath:"=!StartingCommands.txt\original.txt"
)
echo "!starfieldInstallLocation:"=!\Low.ini"
IF EXIST "!starfieldInstallLocation:"=!\Low.ini" && NOT EXISTS "!iniModsPath:"=!Low.ini\original.ini"(
  echo Making a copy of the existing Starfield.ini to be used in compiling
  if not exist "!iniModsPath:\Low.ini\" mkdir "!iniModsPath:\Low.ini\"
  echo F|xcopy /Y /E "!starfieldInstallLocation:"=!\Low.ini" "!iniModsPath:"=!Low.ini\original.ini"
)
echo "!starfieldInstallLocation:"=!\Medium.ini" 
IF EXIST "!starfieldInstallLocation:"=!\Medium.ini" && NOT EXISTS "!iniModsPath:"=!Medium.ini\original.ini"(
  echo Making a copy of the existing Starfield.ini to be used in compiling
  if not exist "!iniModsPath:\Medium.ini\" mkdir "!iniModsPath:\Medium.ini\"
  echo F|xcopy /Y /E "!starfieldInstallLocation:"=!\Medium.ini" "!iniModsPath:"=!Medium.ini\original.ini"
)
echo "!starfieldInstallLocation:"=!\High.ini"
IF EXIST "!starfieldInstallLocation:"=!\High.ini" && NOT EXISTS "!iniModsPath:"=!High.ini\original.ini"(
  echo Making a copy of the existing Starfield.ini to be used in compiling
  if not exist "!iniModsPath:\High.ini\" mkdir "!iniModsPath:\High.ini\"
  echo F|xcopy /Y /E "!starfieldInstallLocation:"=!\High.ini" "!iniModsPath:"=!High.ini\original.ini"
)
echo "!starfieldInstallLocation:"=!\Ultra.ini"
IF EXIST "!starfieldInstallLocation:"=!\Ultra.ini" && NOT EXISTS "!iniModsPath:"=!Ultra.ini\original.ini"(
  echo Making a copy of the existing Starfield.ini to be used in compiling
  if not exist "!iniModsPath:\Ultra.ini\" mkdir "!iniModsPath:\Ultra.ini\"
  echo F|xcopy /Y /E "!starfieldInstallLocation:"=!\Ultra.ini" "!iniModsPath:"=!Ultra.ini\original.ini"
)```

**Comment by vendeta44** [comment]
Ya that folder doesn't exist on my computer. I have a python311 folder there but it doesn't contain a script folder either. 

G:/SteamLibrary/steamapps/common/Starfield
C:/Users/vendeta/Documents/My Games/Starfield

This is what I get when I run that code.

```

G:\>G:\SFmoddin\Release-0.1.1\setup_venv.bat

G:\>echo ----------------------------------------
----------------------------------------

G:\>echo Collecting existing INI files from Game Install
Collecting existing INI files from Game Install

G:\>echo "!starfieldMyGamesLocation:"=!\StarfieldCustom.ini"
"!starfieldMyGamesLocation:"=!\StarfieldCustom.ini"

G:\>IF EXIST "!starfieldMyGamesLocation:" !\StarfieldCustom.ini" && NOT EXISTS "!iniModsPath:"=!StarfieldCustom.ini\original.ini" (

G:\>echo Making a copy of the existing StarfieldCustom.ini to be used in compiling
Making a copy of the existing StarfieldCustom.ini to be used in compiling

G:\>if not exist "!iniModsPath:\StarfieldCustom.ini\" mkdir "!iniModsPath:\StarfieldCustom.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldMyGamesLocation:"=!\StarfieldCustom.ini" "!iniModsPath:"=!StarfieldCustom.ini\original.ini"
File not found - original.ini
0 File(s) copied

G:\>echo "!starfieldMyGamesLocation:"=!\StarfieldPrefs.ini"
"!starfieldMyGamesLocation:"=!\StarfieldPrefs.ini"

G:\>IF EXIST "!starfieldMyGamesLocation:" !\StarfieldPrefs.ini" && NOT EXISTS "!iniModsPath:"=!StarfieldPrefs.ini\original.ini"(

G:\>echo Making a copy of the existing StarfieldPrefs.ini to be used in compiling
Making a copy of the existing StarfieldPrefs.ini to be used in compiling

G:\>if not exist "!iniModsPath:\StarfieldPrefs.ini\" mkdir "!iniModsPath:\StarfieldPrefs.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldMyGamesLocation:"=!\StarfieldPrefs.ini" "!iniModsPath:"=!StarfieldPrefs.ini\original.ini"
File not found - original.ini
0 File(s) copied

G:\>echo "!starfieldMyGamesLocation:"=!\StarfieldHotkeys.ini"
"!starfieldMyGamesLocation:"=!\StarfieldHotkeys.ini"

G:\>IF EXIST "!starfieldMyGamesLocation:" !\StarfieldHotkeys.ini" && NOT EXISTS "!iniModsPath:"=!StarfieldHotkeys.ini\original.ini"(

G:\>echo Making a copy of the existing StarfieldHotkeys.ini to be used in compiling
Making a copy of the existing StarfieldHotkeys.ini to be used in compiling

G:\>if not exist "!iniModsPath:\StarfieldHotkeys.ini\" mkdir "!iniModsPath:\StarfieldHotkeys.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldMyGamesLocation:"=!\StarfieldHotkeys.ini" "!iniModsPath:"=!StarfieldHotkeys.ini\original.ini"
File not found - original.ini
0 File(s) copied

G:\>echo "!starfieldInstallLocation:"=!\Starfield.ini"
"!starfieldInstallLocation:"=!\Starfield.ini"

G:\>IF EXIST "!starfieldInstallLocation:" !\Starfield.ini" && NOT EXISTS "!iniModsPath:"=!Starfield.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\Starfield.ini\" mkdir "!iniModsPath:\Starfield.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\Starfield.ini" "!iniModsPath:"=!Starfield.ini\original.ini"
File not found - original.ini
0 File(s) copied

G:\>echo "!starfieldInstallLocation:"=!\StartingCommands.txt"
"!starfieldInstallLocation:"=!\StartingCommands.txt"

G:\>IF EXIST "!starfieldInstallLocation:" !\StartingCommands.txt" && NOT EXISTS "!iniModsPath:"=!StartingCommands.txt\original.txt"(

G:\>echo Making a copy of the existing StartingCommands.txt to be used in compiling
Making a copy of the existing StartingCommands.txt to be used in compiling

G:\>if not exist "!iniModsPath:\StartingCommands.txt\" mkdir "!iniModsPath:\StartingCommands.txt\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\StartingCommands.txt" "!iniModsPath:"=!StartingCommands.txt\original.txt"
File not found - original.txt
0 File(s) copied

G:\>echo "!starfieldInstallLocation:"=!\Low.ini"
"!starfieldInstallLocation:"=!\Low.ini"

G:\>IF EXIST "!starfieldInstallLocation:" !\Low.ini" && NOT EXISTS "!iniModsPath:"=!Low.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\Low.ini\" mkdir "!iniModsPath:\Low.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\Low.ini" "!iniModsPath:"=!Low.ini\original.ini"
File not found - original.ini
0 File(s) copied

G:\>echo "!starfieldInstallLocation:"=!\Medium.ini"
"!starfieldInstallLocation:"=!\Medium.ini"

G:\>IF EXIST "!starfieldInstallLocation:" !\Medium.ini" && NOT EXISTS "!iniModsPath:"=!Medium.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\Medium.ini\" mkdir "!iniModsPath:\Medium.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\Medium.ini" "!iniModsPath:"=!Medium.ini\original.ini"
File not found - original.ini
0 File(s) copied

G:\>echo "!starfieldInstallLocation:"=!\High.ini"
"!starfieldInstallLocation:"=!\High.ini"

G:\>IF EXIST "!starfieldInstallLocation:" !\High.ini" && NOT EXISTS "!iniModsPath:"=!High.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\High.ini\" mkdir "!iniModsPath:\High.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\High.ini" "!iniModsPath:"=!High.ini\original.ini"
File not found - original.ini
0 File(s) copied

G:\>echo "!starfieldInstallLocation:"=!\Ultra.ini"
"!starfieldInstallLocation:"=!\Ultra.ini"

G:\>IF EXIST "!starfieldInstallLocation:" !\Ultra.ini" && NOT EXISTS "!iniModsPath:"=!Ultra.ini\original.ini"(

G:\>echo Making a copy of the existing Starfield.ini to be used in compiling
Making a copy of the existing Starfield.ini to be used in compiling

G:\>if not exist "!iniModsPath:\Ultra.ini\" mkdir "!iniModsPath:\Ultra.ini\"
The filename, directory name, or volume label syntax is incorrect.

G:\>echo F  | xcopy /Y /E "!starfieldInstallLocation:"=!\Ultra.ini" "!iniModsPath:"=!Ultra.ini\original.ini"
File not found - original.ini
0 File(s) copied

G:\>)```
')```' is not recognized as an internal or external command,
operable program or batch file.
G:\>

```

**Comment by Picklelord** [comment]
you will need to remove the 2 sets of: "\```" from the bat file at the start and end of the section you copied. 
Thasts what this errror is from:
G:\>)\```
')\```'

the python part is only if you need/want to build the exe files yourself, if you want to then follow this next section. 
Otherwise either download the exe files directly from the release on Github and use those instead.
Otherwise if you want to build it yourself, the the issue is likely that you need to install pyinstaller. 
You will just need to run this in cmd: 
pip install pyinstaller
once its installed it will tell you where its installed, which should be that Python311\scripts folder but depending on how it was installed could be in several locations, so use whatever path it gives and set that in the config.ini. 

if you cannot run pip then either the PythonPath isn't in your PATH environment variable or pip isn't installed, look online for tutorials on setting these up if needed.

**Comment by Picklelord** [comment]
Im closing this issue assuming its been resolved, reopen with more details if the issue is still occuring
